### ISSUE TITLE
Setting workspace in new rhai config causes crash

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/wwm#107]
Been trying to figure out how to set the workspace config setting in the new rhai dev build, but can see to get it right. Anytime I set it wwm crashes and then won't start until I remove that setting from my config file.

Here is what I have:
```
workspace 4 #{
  monitor: 1
};
```

I noticed in the documentation it has it listed without the final semicolon, but even if I remove it nothing changes and it still crashes.

**Comment by TimUntersberger** [comment]
fixed in latest dev build
