### ISSUE TITLE
Weird White border around the end on Firefox

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/wwm#108]
I initially thought I was getting this border because I had a rule set for Firefox, but other apps with rules don't have the white border.

When I completely removed the FIrefox rule, the white border still showed up. Exiting wwm and the border goes away, so I believe this must be an issue with wwm rather than Firefox.

![image](https://user-images.githubusercontent.com/13246774/89587445-9e4a4d00-d80f-11ea-8e4f-1c99372ad8b9.png)

**Comment by TimUntersberger** [comment]
For me it is working. 

This is my rule for firefox:
```
rule ".*- Mozilla Firefox|Mozilla Firefox" #{
    has_custom_titlebar: true,
    workspace: 2,
    firefox: true
};
```

Can you try with my rule?

**Comment by keepitsane** [comment]
Putting the rule as you have it exactly causes wwm to crash. Seems like some code for the workspace setting is missing in the current dev build. Even removing the workspace setting and keeping the rest the same I still get the white border.

**Comment by TimUntersberger** [comment]
You should be getting a white border without a rule specifically for firefox, so that's not a problem. I pushed again and the exe works for me now.

**Comment by keepitsane** [comment]
This fixed it thank you! But adding a workspace to a rule still causing wwm to crash. Here is the log file
```
[2020-08-07 10:34:46.606245 -04:00] INFO [src\main.rs:166] 
[2020-08-07 10:34:46.606744 -04:00] INFO [src\main.rs:88] Initializing config
[2020-08-07 10:34:46.607738 -04:00] DEBUG [src\config\rhai\engine.rs:62] Parsing config file
[2020-08-07 10:34:46.612239 -04:00] ERROR [src\main.rs:47] Syntax error: Expecting name of a property (line 22, position 5)
[2020-08-07 10:34:46.612741 -04:00] ERROR [src\main.rs:190] PANIC: unknown
```

**Comment by TimUntersberger** [comment]
Can you show me your config?

**Comment by keepitsane** [comment]
Here is my  `rules.rhai` having trouble specifically with my Spotify rule.
```
ignore "File Explorer";
ignore "Windows Explorer";
ignore "Task Manager";
ignore "This PC";

rule ".*- Google Chrome" #{
    has_custom_titlebar: true,
    chromium: true,
};

rule ".*- Firefox Nightly|Mozilla Firefox$" #{
    has_custom_titlebar: true,
    firefox: true
};

rule ".*- Discord|Discord$" #{
    has_custom_titlebar: true,
};

rule "Spotify (32 bit)" #{
    has_custom_titlebar: true,
    workspace: 6
};

rule ".*- Google Chrome" #{
    has_custom_titlebar: true,
    chromium: true,
};

rule ".*- Visual Studio Code" #{
    has_custom_titlebar: true,
};
```

If you need my other config files let me know. But basically it follows the same structure as the example one.

**Comment by TimUntersberger** [comment]
OHHH.

`workspace` has been renamed to `workspace_id`.

I forgot to update the example, sorry.

**Comment by keepitsane** [comment]
That fixed it. Thanks once again!
