### ISSUE TITLE
Support/document keybindings using super/windows key as modifier

### ISSUE THREAD

**Issue by Pajn** [TimUntersberger/wwm#49]
The readme only lists alt, ctrl and shift as possible modifier keys. I want to map my windows workflow as closely as possible to my linux one and super is the modifier I use for all window management keybindings.

**Comment by TimUntersberger** [comment]
This is sadly not possible as Windows reserves all super key shortcuts for itself.

**Comment by Pajn** [comment]
Okay, that's sad, thank you!
