### ISSUE TITLE
WWM slows down after some time

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/wwm#50]
When staying in work mode WWM slowly slows down. Going out of work mode and reentering it fixes the problem

**Comment by SirWindfield** [comment]
Do you have an idea on why this might happen? Something I can take a look at specifically?

**Comment by TimUntersberger** [comment]
Im currently trying to troubleshoot it myself and don't really know why this is happening. It seems to be happening only when actually using the program as I had it running yesterday when I was out and this problem didn't accure. This makes debugging this really hard.

**Comment by TimUntersberger** [comment]
My idea right now is to find a way too reproduce this or just scan the whole codebase for anything that might be a problem.

**Comment by SirWindfield** [comment]
Pretty sure I found it. I'll open a PR in some minutes :)

**Comment by TimUntersberger** [comment]
I sadly don't think that the drop call was the reason.

**Comment by TimUntersberger** [comment]
I think I have it narrowed down to either one of these three threads:

* [app bar](https://github.com/TimUntersberger/wwm/blob/master/src/app_bar.rs#L221)
* [hot key manager](https://github.com/TimUntersberger/wwm/blob/master/src/hot_key_manager.rs#L74)
* [win event handler](https://github.com/TimUntersberger/wwm/blob/master/src/win_event_handler.rs#L87)

**Comment by SirWindfield** [comment]
I just realized, maybe taking a look into the windows logs might help out here (using the `Event Viewer` windows application, pre-installed).

**Comment by TimUntersberger** [comment]
I think I fixed it! 

I use the `CreateSolidBrush` function to paint the background of the appbar and assumed that the object gets deleted automatically when it is out of scope. In reality you need to explicitly call `DeleteObject` on the handle that gets returned. That is probably also why leaving and entering fixes the problem as all resources related to the appbar get cleaned up when the window gets closed.

I am currently testing the solution.

**Comment by SirWindfield** [comment]
@TimUntersberger Nice catch! You actually inspired me to write one myself to get to know how they work internally :) I am still fletching out the API as I wanted to split off the tile, layout and workspace logic from the rendering code. This might allow other people to re-use the logic and just implement new renderers for other platforms or backends (wayland, x11 etc.).

It might be worth splitting off the appbar into it's own project on the long run, something like `polybar` on linux.

**Comment by TimUntersberger** [comment]
Closing this as I think I fixed it.

**Comment by TimUntersberger** [comment]
I either reintroduced the problem or it was never fixed. I now log the time it takes to paint the appbar and noticed a massive difference in paint time after a while. In the beginning it takes around 1ms to paint but after about an hour of running the paint takes around 20ms.

**Comment by TimUntersberger** [comment]
Fixed by b3f12c2

I thought I fixed it by releasing brushes created by the CreateSolidBrush function, but I missed that I also have to manually release the device context required for the draw functions.
