### ISSUE TITLE
Workspace per Monitor

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/wwm#51]
Currently thinking about whether to have a seperate list of workspaces for each monitor or just one for the whole system.

Just having one list should be easier to implement, but I will need some time to think about the pros and cons of each solution.

**Comment by TimUntersberger** [comment]
I scanned the comments under [this](https://www.reddit.com/r/rust/comments/hg37c5/wwm_windows_window_manager_is_now_feature_complete/) post and found different ways to implement this:

* A workspace spans across all monitors
* A workspace for each monitor

I don't see a reason for not implementing both, but I might find some problems when implementing this.

**Comment by MaikKlein** [comment]
My current use case:

In awesome I have one workspace per monitor with 10 "virtual desktops" per workspace. 
* `alt + {Left/Right}` to switch between monitors

* `ctrl+alt+{Left/Right}` moves a window from the currently focused monitor to the other monitor.

* `ctrl+{0..9}` to switch to the virtual desktop. This is context sensitive based on which monitor is focused.

**Comment by 0b01** [comment]
I use i3 with multiple monitors. The hierarchy of both FancyZones and i3 is monitor > workspace > grid > window. Each monitor has its own workspace so switching workspace in one monitor is independent of other monitors.

**Comment by DavidMtbg** [comment]
I would want to be able to switch workspaces that span all monitors, but also be able to move a layout from one monitor to another monitor.  Whether that's via a workspace or something else, I'm not sure.  However workspaces spanning all monitors would be first priority to me personally.

**Comment by zbidwell** [comment]
I also want to add that this would be super useful for me. My preference would be for each monitor to have its own set of workspaces.

**Comment by TimUntersberger** [comment]
> 
> 
> My current use case:
> 
> In awesome I have one workspace per monitor with 10 "virtual desktops" per workspace.
> 
>     * `alt + {Left/Right}` to switch between monitors
> 
>     * `ctrl+alt+{Left/Right}` moves a window from the currently focused monitor to the other monitor.
> 
>     * `ctrl+{0..9}` to switch between virtual desktops. This is context sensitive based on which monitor is focused.

Do you mean you have only one workspace or do you have multiple? If you have only one then I think "virtual desktops" in awesome would be the same as workspaces in wwm or did I misunderstand something?

**Comment by TimUntersberger** [comment]
> 
> 
> I would want to be able to switch workspaces that span all monitors, but also be able to move a layout from one monitor to another monitor. Whether that's via a workspace or something else, I'm not sure. However workspaces spanning all monitors would be first priority to me personally.

So even though both monitors may use the same workspace, they use different grids (to enable layout switching between monitors)?

**Comment by MaikKlein** [comment]
> Do you mean you have only one workspace or do you have multiple? If you have only one then I think "virtual desktops" in awesome would be the same as workspaces in wwm or did I misunderstand something?

I currently have two monitors, so I have two workspaces.

**Comment by TimUntersberger** [comment]
Ah I think I understand what you mean. 
In the case of WWM a workspace is more like a virtual desktop. 
I believe your use case would be the same as the use case  "workspace per monitor" mentioned above.

**Comment by TimUntersberger** [comment]
@DavidMtbg How exactly would you use workspaces that span all monitors?

**Comment by DavidMtbg** [comment]
What I'm imagining is a combination of workspace pretty monitor and virtual desktops. But with ability to pin a monitor workspace or more to one or more desktops.

For a while, I was thinking that having this work pile virtual desktops would be redundant and should just work in harmony with the Windows feature for this, but I realized that probably wouldn't work very well because of Windows probably not supporting the pinning of a workspace.

**Comment by TimUntersberger** [comment]
I think I completely misunderstood your use case. 

> However workspaces spanning all monitors would be first priority to me personally.

I thought you meant that the workspace starts at the left side of the left most monitor and ends at the right side of the right most monitor. If you open a new window in a new workspace it also spans across all monitors.

**Comment by DavidMtbg** [comment]
I think it's become clearer to me what I was really thinking versus what it would not mean now that I've used WWM more.  So I probably wasn't very clear even what I was thinking of at the time anyway.

**Comment by TimUntersberger** [comment]
Just to summarize your requirements, please tell me if I missed something:

* Assign a workspace to a monitor
* Swap workspaces between monitors

**Comment by DavidMtbg** [comment]
I would add:
- allow for different configurations or sets of workspaces to be displayed together as a unit

**Comment by TimUntersberger** [comment]
I'm going to leave a todo list here that I am going to update whenever something new gets implemented.

- [x] appbar on every monitor
- [x] hide taskbar on every monitor
- [ ] setting for activating multi monitor support
- [ ] keybinding for swapping workspaces between monitors
- [ ] setting for assigning a workspace to a monitor

I'm going to implement the easier use case first (Workspace per monitor) and open a new issue for "Workspace across all monitors"

**Comment by DavidMtbg** [comment]
Thought if something else inspired by your to-do list that you might want to consider: how will focus work between monitor workspaces that are currently displayed? Do you want to add?:
- allow focus to move across displayed monitor workspaces

**Comment by TimUntersberger** [comment]
This would require a massive refactor and I'm not sure whether I'm willing to do this right now. I'll open a seperate issue for that.

**Comment by TimUntersberger** [comment]
There is now a [PR](https://github.com/TimUntersberger/wwm/pull/69) for this which implements multi monitor support based on `workspace per monitor`.
