### ISSUE TITLE
Restart option from system tray icon

### ISSUE THREAD

**Issue by DavidMtbg** [TimUntersberger/wwm#55]
Especially in lieu of an auto-restart when changes to configuration are detected, it would be helpful to have a Restart option on right-click of the system tray icon.  Especially helpful when keybinding for Quit is not working, but still useful outside of that scenario as well.

**Comment by TimUntersberger** [comment]
Do you think that this option is still useful when hot reloading is implemented?

**Comment by DavidMtbg** [comment]
It might be useful when keybindings stop working or something gets odd.  Keybinding is working much better in the code from master branch, but I did have it stop working just once and then I think the app crashed shortly after that, but not a huge deal at this point (and no ideas on what the cause was except that I was doing a lot of testing for #58 at the time).  At any rate, restart would have been useful there (vs. quit from sys tray, and then relaunch).

**Comment by TimUntersberger** [comment]
When something with the keybindings doesn't work you can always leave work mode and reenter it. This unregisters all keybindings and registers them again, but I get what you are saying.

**Comment by TimUntersberger** [comment]
If you have the latest build then you might have a log file named `output.log` file in `%APPDATA%\wwm`.

**Comment by DavidMtbg** [comment]
I'll keep that in mind for future issues, thanks!
