### ISSUE TITLE
Closing a managed app using Alt+F4 leaves empty space in workspace

### ISSUE THREAD

**Issue by DavidMtbg** [TimUntersberger/wwm#58]
This could just be an adjustment that users have to make (use the WWM keybinding and things work fine), but it would be nice if it could be caught and handled.

It also seems to boot other apps out of the workspace sometimes when another app is added to the workspace after this has been done.

Workaround: adding another app to the workspace and then using the keybinding to close the tile helps, but then the "booting" still happens sometimes and also the empty space is still left sometimes as well (after adding and removing a few apps to the workspace to continue testing) - even when the close tile keybinding is used consistently after that initial misuse of Alt+F4.

**Comment by TimUntersberger** [comment]
Which application did you Alt + F4?

**Comment by TimUntersberger** [comment]
If you open Notepad and Alt + F4 does it work for you?

**Comment by DavidMtbg** [comment]
It was Notepad that I was testing with and seeing the issue with.

**Comment by DavidMtbg** [comment]
I'm observing the same thing with Chrome as the first app and then VS Code as the second app that I close with Alt+F4 though.

**Comment by TimUntersberger** [comment]
Hmm this doesn't happen for me. Can you share your config with me?

**Comment by DavidMtbg** [comment]
It's just the default one, but with one change: Taskbar is visible.  I'll share the file a little later though if you still need it.

**Comment by TimUntersberger** [comment]
Never mind I can reproduce it now.

**Comment by TimUntersberger** [comment]
This should be fixed by aa139b8

**Comment by TimUntersberger** [comment]
This fix is included in the latest release

**Comment by DavidMtbg** [comment]
The fix works, but there seems to be a regression in the a8fa72b where I tested this:
In that build, apps spawned on horizontal split create a transparent gap at the top of the tile and what looks like opaque empty padding at the bottom of the tile (see screenshot).

![image](https://user-images.githubusercontent.com/2164372/85962959-7a2e5d00-b981-11ea-9cde-9d94144eb7f1.png)

**Comment by TimUntersberger** [comment]
Is this still happening in the next release for you?

**Comment by TimUntersberger** [comment]
fix it in the development build
