### ISSUE TITLE
Set up a build of main or other branch that testers can get latest binary from

### ISSUE THREAD

**Issue by DavidMtbg** [TimUntersberger/wwm#59]
Clone and build was smooth (partly because I already had Rust set up in VS Code), but some testers might not want to go through that to check fixes before they go out to a release.  Having a Github Action maybe that compiles a beta or something might be helpful.  

Potentially having a testing or beta "ring" might be good to have as well - where those users get beta builds automatically (if auto-update were implemented and enabled).

**Comment by TimUntersberger** [comment]
I guess having a master and development branch where the master branch has all the tested bugfixes and development is just always the most recent version should be enough for now. I don't want to overcomplicate this right now.

The idea with github actions sounds very good. 

Do you have any previous experience with setting something similiar up?

**Comment by TimUntersberger** [comment]
There is now a github action for the development branch.

Whenever something gets pushed to the development branch, a new release with tag 'Next' and title 'Development Build' gets created.
