### ISSUE TITLE
After layout gets messed up by an app with a splash window (#60), turning off Working mode crashes WWM

### ISSUE THREAD

**Issue by DavidMtbg** [TimUntersberger/wwm#61]
To repro:
1. Run WWM.
2. Float Chrome in a workspace.
3. Launch Excel.  This results in #60.
4. Turn off Working Mode using keybinding.  When you try to turn it back on, it doesn't work.  This is because WWM has crashed.

**Comment by TimUntersberger** [comment]
This should also be fixed by  96abbea
