### ISSUE TITLE
Unable to do anything

### ISSUE THREAD

**Issue by 0b01** [TimUntersberger/wwm#77]
I am using the latest build in release and the example config with two monitors but none of the keybindings works. Also Alt+H opens Help menu in vscode.

**Comment by TimUntersberger** [comment]
Is wwm still running, but just not responding?

Did you try entering work mode via the following shortcut?

```yaml
type: ToggleWorkMode
key: Alt+Control+W
```

Because `work_mode` is set to true you should be able to use the keybindings right away, maybe I somehow broke the initial loading of this setting.

**Comment by basedtho** [comment]
Windows Defender won't let me run this program 😟

**Comment by TimUntersberger** [comment]
Are you getting [this](https://www.google.com/search?q=windows+defender+unknown+publisher&client=firefox-b-d&sxsrf=ALeKk03fOVpaybXzjf9ctIOsTQ-IU5n9SA:1594877265182&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiswOfmhNHqAhXByKYKHUjdAWcQ_AUoAXoECBMQAw&biw=1920&bih=938#imgrc=IxtyHXFskX2wFM)? You have to click more info to run the program.

**Comment by TimUntersberger** [comment]
Closing this as the author has not responded in a long time and I can't reproduce the issue.
