### ISSUE TITLE
multi_monitor issues when using monitors that are different resolutions

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/wwm#86]
The display_app_bar seems to not reflect the resolution of the monitor it is being displayed on when using multi_monitor and instead just takes the primary monitors. 

My main monitor is an ultrawide monitor and my secondary monitors are not. The workspace numbers show up properly on the left corner of each monitor, however the clock is offset further to the right on the display that is smaller then my primary and the date is cut off entirely.

![wwm_issue_app_bar](https://user-images.githubusercontent.com/13246774/88603985-63445e80-d044-11ea-8ad1-2f73068d9718.png)

**Comment by TimUntersberger** [comment]
This should actually already respect the resolution of each monitor. I can't really reproduce this as I only have 2 monitors of the same size.

The code that is responsible for loading the different monitors is in the `display.rs` file. If you look at the `new` method of the `Display` struct you will be able to see which resolution each monitor is set to.

I'd need your help on this issue.

**Comment by ramirezmike** [comment]
I might be able to take a look at this later today as I mainly use wwm on a laptop plugged into a monitor large monitor. That said, I suspect the issue is in src/app_bar.rs's draw_datetime function. 

In it, it's sizing the date based off of only the primary display.

```let display = get_primary_display();```

Then

```rect.left = display.width() / 2 - (size.cx / 2) - 10;
rect.right = display.width() / 2 + (size.cx / 2) + 10;```


Also, keepitsane pointed out that it's really the date display that is off.

I also noticed this issue when switching from using my monitor to unplugging and just using the laptop screen. I think it saves what the primary display _was_ and sizes everything based on that, but, there are other issues like the placement of the bar. I can dig into that more later and document anything significant.

**Comment by TimUntersberger** [comment]
@ramirezmike

> In it, it's sizing the date based off of only the primary display.

Haha, I forgot about that when developing the multi monitor support. Nice catch! 

Oh I never thought about what happens when a monitor gets unplugged. This is currently results in unknown behaviour. 

Is wwm still working after you unplug your monitor?

**Comment by TimUntersberger** [comment]
The latest dev build should now contain a fix.

**Comment by ramirezmike** [comment]
@TimUntersberger 
> Oh I never thought about what happens when a monitor gets unplugged. This is currently results in unknown behaviour.
> 
> Is wwm still working after you unplug your monitor?

So, my setup is a laptop plugged into a monitor and I keep the laptop screen on but use the monitor as my primary display. I also keep multi_monitor set to false as I like to keep my laptop screen essentially "pinned" with a chat program. When I unplug the monitor with a couple workspaces set up wwm keeps running and the workspaces just move over to the laptop screen, but they keep the same size as they were while on the monitor. There's also some weirdness with the taskbar/appbar but I can resolve that by just using those keybindings I added hah. I haven't tried to see what happens with multi_monitor set to true.

**Comment by TimUntersberger** [comment]
@ramirezmike I'll create a seperate [issue](https://github.com/TimUntersberger/wwm/issues/90) for that
