### ISSUE TITLE
Monitor numbering changes everytime the system is rebooted

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/wwm#91]
In the newest dev build that includes the multi monitor task bar fix. It seems that the monitor number is changing whenever wwm is restarted fresh. This is messing up workspaces config and move to monitor hotkeys.

[#85](https://github.com/TimUntersberger/wwm/issues/85)

**Comment by keepitsane** [comment]
After some additional testing it seems this only happens after a system reboot, the monitor numbering is changing.

**Comment by TimUntersberger** [comment]
That's bad. This was one of my concerns when implementing this via indices. This is probably, because it is not guaranteed that your displays get detected by windows in the same order every time (even though on my machine it is always the same).

**Comment by TimUntersberger** [comment]
Accidently closed the issue

**Comment by keepitsane** [comment]
If you would like me to collect some additional information with WinSpy, please let me know I can continue to help debug this issue.

**Comment by TimUntersberger** [comment]
I think we will have to change from the monitor "index" to the monitor name when referencing a monitor. I don't think that indices are the right answer anymore. Something I could try is calculate the order myself, but this would then assume a specific ordering of monitors (like left -> right and up -> down)

**Comment by TimUntersberger** [comment]
> Something I could try is calculate the order myself, but this would then assume a specific ordering of monitors (like left -> right and up -> down)

After thinking about this some time, I believe that this could be a very viable and convenient option.

Do you notice any problems with this approach?

**Comment by keepitsane** [comment]
Looks like there is no simple pre-rolled solution for this problem. Here is a thread I found on this issue https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/668e3cf9-4e00-4b40-a6f8-c7d2fc1afd39/how-can-i-retrieve-monitor-information

Not sure why Microsoft won't provide the monitor index that Windows generates. I think also long as in the method that you create to calculate your own indices the workspace config settings can be permanently tied to a specific monitor. A problem I think you may run into is specifically with issue #90, as if the monitor gets turned off or unplugged you need to make sure that wwm doesn't think that it is a completely different monitor when it is turned back on. For example as you know my setup has three monitors and lets say I set workspaces 3 to show up on monitor 2. Then if I turn off monitor 2 or unplug it, currently what happens is wwm thinks it is a new monitor and will reassign it as monitor 3 which messes up the my workspace config. 

The method you use to calculate needs to also consider specific details about the monitor itself so it can build a long term map of the connected monitors. Otherwise, you will just run into the same problem as using the EnumDisplayNumbers. Perhaps if you feel this is a bit too complex for you to tackle right now, a simple alternative could be allow the user to manual tell wwm the monitor number if it gets messed up. For example, if my monitor 2 changes to 3 I can run a "ChangeMonitorNumber" function that moves all the active workspaces and assigned workspaces to another display similar in a sense to the "MoveWorkspaceToMonitor" function. Obviously this is more of a temporary fix then a long term solution, but figured I would suggest it. Hope that helps and thanks for taking the time to fix these issues so quickly!

**Comment by TimUntersberger** [comment]
Im thinking about recalculating the indices everytime a monitor gets added/removed since this shouldn't be really expensive to do. This should prevent the indices from getting messed up. Right now I don't really see any problems with this, so I am just going to implement it and see what it feels like.

Little explanation on how I would calculate this:

The monitors are all part of a big "virtual monitor". The primary monitor starts at (0, 0) and for example a monitor to the left starts at (-1920, 0). If I then order these in the correct way I could theoretically calculate the correct index for each monitor.

**Comment by keepitsane** [comment]
Oh I see now that is actually pretty clever. Just make one big map and then subdivide that based on each monitors resolution. Interested to see if it works out.

**Comment by TimUntersberger** [comment]
The dev build now contains my attempt at ordering the monitors.

The indices start at the leftmost/topmost and end at the rightmost/bottommost.

You can even play around with the indices by moving the monitors in the display settings if you wish to do so.

**Comment by keepitsane** [comment]
Windows really hates the latest dev build. In previous builds I would still get the smart screen message that allowed me to select run anyways. Now Windows Defender immediately labels it as a severe threat and deletes the exe upon download. 
Here is the message it gives Behavior:Win32/Execution.IF!ml

![windows_defender_wwm](https://user-images.githubusercontent.com/13246774/89106208-da3b7780-d3f5-11ea-9a21-80b94a287d4b.png)

I can open another issue if you would like, but figure it could worry people if there was suspicious that this is malicious software so decided not to for now.

**Comment by TimUntersberger** [comment]
Have you tried redownloading the exe? Someone had an error like this before and after researching this a bit I found out that Windows 10 uses a bit of machine learning for detecting common attack patterns and this can cause false errors. I don't know how to fix this to be honest.

**Comment by keepitsane** [comment]
Yeah I have it won't even let me download it and when I tell Windows to ignore it the exe still gets deleted. The previous build works fine though.

**Comment by TimUntersberger** [comment]
Windows 10 is really annoying :/

Are you perhaps using a Windows S version?

**Comment by keepitsane** [comment]
I am not. I am currently running Windows 10 Pro on and insider edition build. The last build didn't get flagged as a virus, so it must be something in the code from the last two commits (I think) that got added to the latest build is causing problems. I think the only way to figure that out is just comment code out until it can run. I can help if you would like to test for you. 

If I had to guess it could be wwm accessing the files that contain the monitor information that is possibly triggering it. Just to clarify this is different from the Windows Defender smartscreen warning that allows you to click "run anyways" as mentioned here #77. Windows defender thinks wwm is like a trojan virus or something similar.

**Comment by TimUntersberger** [comment]
I was more talking about #81.

This person had a similar problem and he couldn't reproduce it anymore after some time. I am guessing that you can't really test this by commenting out code until it happens again, because it would be weird if Windows would complain about your own compiled code.

Please tell me if it suddenly works again.

**Comment by keepitsane** [comment]
Yeah that is true I guess. Been testing the new builds and windows defender seems to have stopped complaining, so must be just a hit or miss like you mentioned.

But going back  to the original topic for this issue, the display number is still not consistent. I don't really have any metrics to backup this claim, but I feel the new custom calculated solution seems to be even more random compared to the EnumDisplayNumbers. I the only way I can force it back into the correct order is turning my monitors on and off again and turn them back on in a specific order to get the number order I want. I will have some extra free time this week and will try to dedicate some research time to see how other applications implement similar functionality and will report back.

**Comment by TimUntersberger** [comment]
This shouldn't be random. As long as you don't move your monitors in the display settings you should have a consistent result.

The `sort_by` call in [this](https://github.com/TimUntersberger/wwm/blob/7ccbd31cbbe31377889b5438f447b54765e05d90/src/display.rs#L79) line is responsible for ordering the monitors. 

Could you please check whether you are getting consistent results?

**Comment by keepitsane** [comment]
I have no idea what I changed, but it seems everything has been working properly in my last few days of testing. I am going to go ahead and close this issue now. Thanks!
