### ISSUE TITLE
Configurable "Minimum Window Size" check before managing a new window

### ISSUE THREAD

**Issue by ramirezmike** [TimUntersberger/wwm#95]
I've had some success setting up rules to ignore alerts, notifications or "sub-windows" spawned by apps but sometimes the names are tricky or too dynamic to write rules for. It's usually not a big deal to quickly "unmanage" these windows but it would be nice to have a configurable minimum size that a window has to be greater-than or equal to before wwm grabs it. 

A good example is when copying a large file to a drive, I'll usually end up with a tile dedicated to a progress bar I don't really want to actively watch. Not sure if this is a separate issue, but when that happens I sometimes can't kill the tile and have to use task manger to close it, but that just might be that the managing aspect of wwm forces the window to behave differently than it was designed?

**Comment by TimUntersberger** [comment]
Added `min_width` and `min_height`.
