### ISSUE TITLE
Shortcut to minimize window

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/wwm#97]
What  is the suggested method for when I want to hide a window, but don't want to quit the tile entirely? If no solution exists maybe a shortcut can be added to minimize the current focused tile.

**Comment by TimUntersberger** [comment]
The best way right now is to just use a `ToggleFloatingMode` keybinding. The problem with supporting minimize is what happens when you have 2 windows minimized in a workspace?

**Comment by keepitsane** [comment]
Couldn't minimized windows be brought back using Windows built-in Alt+Tab window switcher?

**Comment by TimUntersberger** [comment]
I think I misunderstood your feature request. Do you mean something like the `CloseTile` keybinding, but just for minimizing?

**Comment by keepitsane** [comment]
Yes that is correct. The shortcut in Windows is Window Key + Down Arrow twice which is really that great. So yes like CloseTile, but does not quit the window and minimizes to taskbar instead.

**Comment by TimUntersberger** [comment]
That's really simple then. I will add this alter today.

**Comment by TimUntersberger** [comment]
Latest dev build contains this feature.
